### ISSUE TITLE
trying to run the testing code but core dumped

### ISSUE THREAD

**Issue by LCA-0907** [SirisAvishek/Scene_Context_Aware_Saliency#2]
Hi, I downloaded the weights of the trained model and tried to run Test_SC_Model.py on my dataset but ran in to some problems, can any one help me?
The error messages are below

> Config 'models/sc_model.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "Test360.py", line 42, in <module>
    predictor = DefaultPredictor(cfg)
  File "/media/facebook/E/Elsa/detectron2/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/media/facebook/E/Elsa/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/facebook/anaconda3/envs/detectron2/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 155, in load
    checkpoint = self._load_file(path)
  File "/media/facebook/E/Elsa/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 88, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/home/facebook/anaconda3/envs/detectron2/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 252, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/home/facebook/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/facebook/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 756219 more bytes. The file might be corrupted.
*** Error in `python': corrupted double-linked list: 0x000055b1876c7720 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7ff1a6c4c7f5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7e6fd)[0x7ff1a6c536fd]
/lib/x86_64-linux-gnu/libc.so.6(+0x80688)[0x7ff1a6c55688]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff1a6c5958c]
...

7ff979e5c000-7ff979e5d000 r--p 00025000 08:31 11147586                   /lib/x86_64-linux-gnu/ld-2.23.so
7ff979e5d000-7ff979e5e000 rw-p 00026000 08:31 11147586                   /lib/x86_64-linux-gnu/ld-2.23.so
7ff979e5e000-7ff979e5f000 rw-p 00000000 00:00 0 
7ffe4b340000-7ffe4b360000 rwxp 00000000 00:00 0                          [stack]
7ffe4b360000-7ffe4b361000 rw-p 00000000 00:00 0 
7ffe4b39b000-7ffe4b39e000 r--p 00000000 00:00 0                          [vvar]
7ffe4b39e000-7ffe4b3a0000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by LCA-0907** [comment]
Sorry, I found that I didn't download the pretrain model completely.
Downloaded it again and it works now.
